# Generated by Django 4.2.1 on 2023-07-27 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("myfrtsite", "0002_userinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={"verbose_name": "网站用户管理", "verbose_name_plural": "网站用户管理"},
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="phoneNum",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="username",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(
                default=django.utils.timezone.now,
                max_length=254,
                unique=True,
                verbose_name="电子邮箱",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "未知"), (1, "男"), (2, "女")], default=0, verbose_name="性别"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="last_login_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后一次登陆的时间"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="modify_time",
            field=models.DateTimeField(auto_now=True, verbose_name="最后一次修改的时间"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=128,
                unique=True,
                verbose_name="用户名",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=256, verbose_name="密码"),
        ),
    ]
