# Generated by Django 4.2.1 on 2023-07-27 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myfrtsite", "0003_alter_userinfo_options_remove_userinfo_phonenum_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserInfo",
            new_name="SiteUser",
        ),
    ]
