# Generated by Django 4.2.3 on 2023-08-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfrtsite', '0005_alter_siteuser_email_alter_siteuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('result', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
