# Generated by Django 4.2.3 on 2023-08-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfrtsite', '0006_sumtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user_avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='intro',
            field=models.TextField(blank=True, max_length=500, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='phone',
            field=models.EmailField(blank=True, max_length=20, verbose_name='phone'),
        ),
    ]
